### ISSUE TITLE
Vendor CNI instead of expecting a working version

### ISSUE THREAD

**Issue by alban** [kinvolk/kubeadm-nspawn#39]
#36 relies on the `bridge` binary from CNI. At the moment, it assumes CNI master compiles and works but that's currently not the case. kubeadm-nspawn should vendor a CNI version that works and compile it (as part of the `make`) and use it.

It would also make the README.md simpler.

**Comment by alban** [comment]
Actually, CNI is vendored but #36 does not seem to use the vendored version and relies on CNI_PATH...

**Comment by robertgzr** [comment]
Closed in favour of running `go get github.com/containernetworking/plugins/...`
